apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: monitoring
spec:
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
    spec:
      containers:
        - name: node-app
          image: yuriyvorobyov96/express-template:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always