scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['app:3000'] # for Docker
      # - targets: ['localhost:3000'] # for local Linux
      # - targets: ["docker.for.mac.host.internal:3000"] # for local Mac
      # - targets: ["docker.for.win.localhost:3000"] # for local Windows
